# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\"!\n\tDataPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"x\n\rMapperRequest\x12\x14\n\x0cnum_reducers\x18\x01 \x01(\x05\x12\x15\n\rnum_centroids\x18\x02 \x01(\x05\x12\x12\n\ninput_file\x18\x03 \x01(\t\x12&\n\tcentroids\x18\x04 \x03(\x0b\x32\x13.Centroid_Point_Map\"<\n\x0eMapperResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11intermediate_file\x18\x02 \x01(\t\"U\n\x0eReducerRequest\x12\x14\n\x0cnum_reducers\x18\x01 \x01(\x05\x12\x13\n\x0bnum_mappers\x18\x02 \x01(\x05\x12\x18\n\x10mapper_base_port\x18\x03 \x01(\x05\"N\n\x0fReducerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12*\n\rnew_centroids\x18\x02 \x03(\x0b\x32\x13.Centroid_Point_Map\"%\n\x0fGetInputRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\"D\n\x12\x43\x65ntroid_Point_Map\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\x12\x19\n\x05point\x18\x02 \x01(\x0b\x32\n.DataPoint\"U\n\x10GetInputResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x30\n\x13\x63\x65ntroid_point_list\x18\x02 \x03(\x0b\x32\x13.Centroid_Point_Map2\xa2\x01\n\x06Master\x12\x30\n\x0bStartMapper\x12\x0e.MapperRequest\x1a\x0f.MapperResponse\"\x00\x12\x33\n\x0cStartReducer\x12\x0f.ReducerRequest\x1a\x10.ReducerResponse\"\x00\x12\x31\n\x08GetInput\x12\x10.GetInputRequest\x1a\x11.GetInputResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAPOINT']._serialized_start=16
  _globals['_DATAPOINT']._serialized_end=49
  _globals['_MAPPERREQUEST']._serialized_start=51
  _globals['_MAPPERREQUEST']._serialized_end=171
  _globals['_MAPPERRESPONSE']._serialized_start=173
  _globals['_MAPPERRESPONSE']._serialized_end=233
  _globals['_REDUCERREQUEST']._serialized_start=235
  _globals['_REDUCERREQUEST']._serialized_end=320
  _globals['_REDUCERRESPONSE']._serialized_start=322
  _globals['_REDUCERRESPONSE']._serialized_end=400
  _globals['_GETINPUTREQUEST']._serialized_start=402
  _globals['_GETINPUTREQUEST']._serialized_end=439
  _globals['_CENTROID_POINT_MAP']._serialized_start=441
  _globals['_CENTROID_POINT_MAP']._serialized_end=509
  _globals['_GETINPUTRESPONSE']._serialized_start=511
  _globals['_GETINPUTRESPONSE']._serialized_end=596
  _globals['_MASTER']._serialized_start=599
  _globals['_MASTER']._serialized_end=761
# @@protoc_insertion_point(module_scope)
